In [21]:
#bai 1
image = [[[255, 0, 0], [0, 255, 0], [0, 0, 255]],
         [[255, 255, 0], [0, 255, 255], [255, 0, 255]],
         [[128, 128, 128], [64, 64, 64], [192, 192, 192]]]

def gray(input_pixel: list[int]):
    return 0.299*input_pixel[0] + 0.587*input_pixel[1] + 0.114*input_pixel[2]

thresh = 128
B = [[0, 0, 0],
     [0, 0, 0],
     [0, 0, 0]]
G = [[0, 0, 0],
     [0, 0, 0],
     [0, 0, 0]]

### a. gray matrix
for i in range(len(image)):
    for j in range(len(image[i])):
        G[i][j] = round(gray(image[i][j]), 3)
print(G)
### b. binary matrix
for i in range(len(image)):
    for j in range(len(image[i])):
        if gray(image[i][j]) > thresh:
            B[i][j] = 1
        else:
            B[i][j] = 0
print(B)

[[76.245, 149.685, 29.07], [225.93, 178.755, 105.315], [128.0, 64.0, 192.0]]
[[0, 1, 0], [1, 1, 0], [0, 0, 1]]


In [24]:
# bai 2
G = [[76, 150, 29],
     [225, 178, 105],
     [128, 64, 92]]

### a. tang do sang
G1 = [[0, 0, 0],
      [0, 0, 0],
      [0, 0, 0]]
beta = 50
for i in range(len(G)):
    for j in range(len(G[i])):
        if G[i][j] + beta >= 255:
            G1[i][j] = 255
        else:
            G1[i][j] = G[i][j] + beta
print(G1)

### b. tang tuong phan
gamma = 1.2
G2 = [[0, 0, 0],
      [0, 0, 0],
      [0, 0, 0]]
for i in range(len(G)):
    for j in range(len(G[i])):
        if G[i][j]*gamma + beta >= 255:
            G2[i][j] = 255
        else:
            G2[i][j] = round(G[i][j]*gamma + beta, 3)
print(G2)

[[126, 200, 79], [255, 228, 155], [178, 114, 142]]
[[141.2, 230.0, 84.8], [255, 255, 176.0], [203.6, 126.8, 160.4]]


In [19]:
#bai 3
import numpy as np

A = np.array([
    [0, 0, 1, 0],
    [0, 1, 1, 1],
    [0, 1, 1, 1],
    [1, 0, 1, 0]])
B = np.array([
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0]])

for i in range(len(A)-1):
    if i == 0:
        continue
    for j in range(len(A[i])-1):
        if j == 0:
            continue
        sigma = A[i][j-1] + A[i][j+1] + A[i-1][j-1] + A[i-1][j+1] + A[i+1][j-1] + A[i+1][j+1] + A[i-1][j] + A[i+1][j]
        if sigma < 8:
            B[i][j] = 0
        else:
            B[i][j] = A[i][j]
print(B)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
